//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Role {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblIsDeleted;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblOrderSort;
	protected global::System.Web.UI.WebControls.Label lblEnabled;
	protected global::System.Web.UI.WebControls.Label lblCreateId;
	protected global::System.Web.UI.WebControls.Label lblCreateBy;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblModifyId;
	protected global::System.Web.UI.WebControls.Label lblModifyBy;
	protected global::System.Web.UI.WebControls.Label lblModifyTime;


       
    }
}
