//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.TopicDetail {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtTopicId;
		protected global::System.Web.UI.WebControls.TextBox txttdLogo;
		protected global::System.Web.UI.WebControls.TextBox txttdName;
		protected global::System.Web.UI.WebControls.TextBox txttdContent;
		protected global::System.Web.UI.WebControls.TextBox txttdDetail;
		protected global::System.Web.UI.WebControls.TextBox txttdSectendDetail;
		protected global::System.Web.UI.WebControls.CheckBox chktdIsDelete;
		protected global::System.Web.UI.WebControls.TextBox txttdRead;
		protected global::System.Web.UI.WebControls.TextBox txttdCommend;
		protected global::System.Web.UI.WebControls.TextBox txttdGood;
		protected global::System.Web.UI.WebControls.TextBox txttdCreatetime;
		protected global::System.Web.UI.WebControls.TextBox txttdUpdatetime;
		protected global::System.Web.UI.WebControls.TextBox txttdTop;
		protected global::System.Web.UI.WebControls.TextBox txttdAuthor;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
