//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.TopicDetail {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblTopicId;
	protected global::System.Web.UI.WebControls.Label lbltdLogo;
	protected global::System.Web.UI.WebControls.Label lbltdName;
	protected global::System.Web.UI.WebControls.Label lbltdContent;
	protected global::System.Web.UI.WebControls.Label lbltdDetail;
	protected global::System.Web.UI.WebControls.Label lbltdSectendDetail;
	protected global::System.Web.UI.WebControls.Label lbltdIsDelete;
	protected global::System.Web.UI.WebControls.Label lbltdRead;
	protected global::System.Web.UI.WebControls.Label lbltdCommend;
	protected global::System.Web.UI.WebControls.Label lbltdGood;
	protected global::System.Web.UI.WebControls.Label lbltdCreatetime;
	protected global::System.Web.UI.WebControls.Label lbltdUpdatetime;
	protected global::System.Web.UI.WebControls.Label lbltdTop;
	protected global::System.Web.UI.WebControls.Label lbltdAuthor;


       
    }
}
