//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Sfc_Mitem {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblMitemCode;
	protected global::System.Web.UI.WebControls.Label lblMitemName;
	protected global::System.Web.UI.WebControls.Label lblMitemDesc;
	protected global::System.Web.UI.WebControls.Label lblMitemType;
	protected global::System.Web.UI.WebControls.Label lblBrand;
	protected global::System.Web.UI.WebControls.Label lblBuyer;
	protected global::System.Web.UI.WebControls.Label lblDutyPerson;
	protected global::System.Web.UI.WebControls.Label lblSupplierId;
	protected global::System.Web.UI.WebControls.Label lblDefaultInvId;
	protected global::System.Web.UI.WebControls.Label lblUom;
	protected global::System.Web.UI.WebControls.Label lblDateTimeCreated;
	protected global::System.Web.UI.WebControls.Label lblUserCreator;
	protected global::System.Web.UI.WebControls.Label lblDateTimeModified;
	protected global::System.Web.UI.WebControls.Label lblUserModified;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblOrgId;


       
    }
}
