//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Inv_Inv_Info {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtId;
		protected global::System.Web.UI.WebControls.TextBox txtInvCode;
		protected global::System.Web.UI.WebControls.TextBox txtInvName;
		protected global::System.Web.UI.WebControls.TextBox txtInvDesc;
		protected global::System.Web.UI.WebControls.TextBox txtInvAddress;
		protected global::System.Web.UI.WebControls.TextBox txtVolume;
		protected global::System.Web.UI.WebControls.TextBox txtVolumeUnit;
		protected global::System.Web.UI.WebControls.TextBox txtDateTimeCreated;
		protected global::System.Web.UI.WebControls.TextBox txtUserCreator;
		protected global::System.Web.UI.WebControls.TextBox txtDateTimeModified;
		protected global::System.Web.UI.WebControls.TextBox txtUserModified;
		protected global::System.Web.UI.WebControls.CheckBox chkState;
		protected global::System.Web.UI.WebControls.TextBox txtOrgId;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
