//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Inv_Bill_Hd {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblBillType;
	protected global::System.Web.UI.WebControls.Label lblPlanQty;
	protected global::System.Web.UI.WebControls.Label lblActualQty;
	protected global::System.Web.UI.WebControls.Label lblSrcBillId;
	protected global::System.Web.UI.WebControls.Label lblSrcBillNo;
	protected global::System.Web.UI.WebControls.Label lblInvId;
	protected global::System.Web.UI.WebControls.Label lblInvCode;
	protected global::System.Web.UI.WebControls.Label lblInvName;
	protected global::System.Web.UI.WebControls.Label lblInvAddress;
	protected global::System.Web.UI.WebControls.Label lblRcvUser;
	protected global::System.Web.UI.WebControls.Label lblRcvDateTime;
	protected global::System.Web.UI.WebControls.Label lblRcvReason;
	protected global::System.Web.UI.WebControls.Label lblRcvAddress;
	protected global::System.Web.UI.WebControls.Label lblBillStatus;
	protected global::System.Web.UI.WebControls.Label lblDateTimeCreated;
	protected global::System.Web.UI.WebControls.Label lblUserCreator;
	protected global::System.Web.UI.WebControls.Label lblDateTimeModified;
	protected global::System.Web.UI.WebControls.Label lblUserModified;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblOrgId;


       
    }
}
