//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Sys_Module {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblModuleType;
	protected global::System.Web.UI.WebControls.Label lblModuleCode;
	protected global::System.Web.UI.WebControls.Label lblModuleName;
	protected global::System.Web.UI.WebControls.Label lblModuleDesc;
	protected global::System.Web.UI.WebControls.Label lblModuleConfig;
	protected global::System.Web.UI.WebControls.Label lblPath;
	protected global::System.Web.UI.WebControls.Label lblDateTimeCreated;
	protected global::System.Web.UI.WebControls.Label lblUserCreator;
	protected global::System.Web.UI.WebControls.Label lblDateTimeModified;
	protected global::System.Web.UI.WebControls.Label lblUserModified;
	protected global::System.Web.UI.WebControls.Label lblState;


       
    }
}
