//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Inv_Onhand_Qty {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtId;
		protected global::System.Web.UI.WebControls.TextBox txtMitemId;
		protected global::System.Web.UI.WebControls.TextBox txtInvId;
		protected global::System.Web.UI.WebControls.TextBox txtDistrictId;
		protected global::System.Web.UI.WebControls.TextBox txtLocId;
		protected global::System.Web.UI.WebControls.TextBox txtTrans_Qty;
		protected global::System.Web.UI.WebControls.TextBox txtDateTimeCreated;
		protected global::System.Web.UI.WebControls.TextBox txtUserCreator;
		protected global::System.Web.UI.WebControls.TextBox txtDateTimeModified;
		protected global::System.Web.UI.WebControls.TextBox txtUserModified;
		protected global::System.Web.UI.WebControls.CheckBox chkState;
		protected global::System.Web.UI.WebControls.TextBox txtOrgId;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
