//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.sysUserInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lbluID;
		protected global::System.Web.UI.WebControls.TextBox txtuLoginName;
		protected global::System.Web.UI.WebControls.TextBox txtuLoginPWD;
		protected global::System.Web.UI.WebControls.TextBox txtuRealName;
		protected global::System.Web.UI.WebControls.TextBox txtuStatus;
		protected global::System.Web.UI.WebControls.TextBox txtuRemark;
		protected global::System.Web.UI.WebControls.TextBox txtuCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtuUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtuLastErrTime;
		protected global::System.Web.UI.WebControls.TextBox txtuErrorCount;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtsex;
		protected global::System.Web.UI.WebControls.TextBox txtage;
		protected global::System.Web.UI.WebControls.TextBox txtbirth;
		protected global::System.Web.UI.WebControls.TextBox txtaddr;
		protected global::System.Web.UI.WebControls.CheckBox chktdIsDelete;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
