//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.sysUserInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluID;
	protected global::System.Web.UI.WebControls.Label lbluLoginName;
	protected global::System.Web.UI.WebControls.Label lbluLoginPWD;
	protected global::System.Web.UI.WebControls.Label lbluRealName;
	protected global::System.Web.UI.WebControls.Label lbluStatus;
	protected global::System.Web.UI.WebControls.Label lbluRemark;
	protected global::System.Web.UI.WebControls.Label lbluCreateTime;
	protected global::System.Web.UI.WebControls.Label lbluUpdateTime;
	protected global::System.Web.UI.WebControls.Label lbluLastErrTime;
	protected global::System.Web.UI.WebControls.Label lbluErrorCount;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblsex;
	protected global::System.Web.UI.WebControls.Label lblage;
	protected global::System.Web.UI.WebControls.Label lblbirth;
	protected global::System.Web.UI.WebControls.Label lbladdr;
	protected global::System.Web.UI.WebControls.Label lbltdIsDelete;


       
    }
}
