//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.PasswordLib {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblPLID;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDeleted;
		protected global::System.Web.UI.WebControls.TextBox txtplURL;
		protected global::System.Web.UI.WebControls.TextBox txtplPWD;
		protected global::System.Web.UI.WebControls.TextBox txtplAccountName;
		protected global::System.Web.UI.WebControls.TextBox txtplStatus;
		protected global::System.Web.UI.WebControls.TextBox txtplErrorCount;
		protected global::System.Web.UI.WebControls.TextBox txtplHintPwd;
		protected global::System.Web.UI.WebControls.TextBox txtplHintquestion;
		protected global::System.Web.UI.WebControls.TextBox txtplCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtplUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtplLastErrTime;
		protected global::System.Web.UI.WebControls.TextBox txttest;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
