//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.PasswordLib {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPLID;
	protected global::System.Web.UI.WebControls.Label lblIsDeleted;
	protected global::System.Web.UI.WebControls.Label lblplURL;
	protected global::System.Web.UI.WebControls.Label lblplPWD;
	protected global::System.Web.UI.WebControls.Label lblplAccountName;
	protected global::System.Web.UI.WebControls.Label lblplStatus;
	protected global::System.Web.UI.WebControls.Label lblplErrorCount;
	protected global::System.Web.UI.WebControls.Label lblplHintPwd;
	protected global::System.Web.UI.WebControls.Label lblplHintquestion;
	protected global::System.Web.UI.WebControls.Label lblplCreateTime;
	protected global::System.Web.UI.WebControls.Label lblplUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblplLastErrTime;
	protected global::System.Web.UI.WebControls.Label lbltest;


       
    }
}
