//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Inv_Loc {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblLocCode;
	protected global::System.Web.UI.WebControls.Label lblLocName;
	protected global::System.Web.UI.WebControls.Label lblLocDesc;
	protected global::System.Web.UI.WebControls.Label lblLocStatus;
	protected global::System.Web.UI.WebControls.Label lblLocOrder;
	protected global::System.Web.UI.WebControls.Label lblVolume;
	protected global::System.Web.UI.WebControls.Label lblVolumeUnit;
	protected global::System.Web.UI.WebControls.Label lblDateTimeCreated;
	protected global::System.Web.UI.WebControls.Label lblUserCreator;
	protected global::System.Web.UI.WebControls.Label lblDateTimeModified;
	protected global::System.Web.UI.WebControls.Label lblUserModified;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblOrgId;
	protected global::System.Web.UI.WebControls.Label lblDistrictId;
	protected global::System.Web.UI.WebControls.Label lblInvId;


       
    }
}
