//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Sfc_Customer {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblCustomerCode;
	protected global::System.Web.UI.WebControls.Label lblCustomerName;
	protected global::System.Web.UI.WebControls.Label lblCustomerShortName;
	protected global::System.Web.UI.WebControls.Label lblCustomerPhone;
	protected global::System.Web.UI.WebControls.Label lblCustomerWebchat;
	protected global::System.Web.UI.WebControls.Label lblEnterpriseName;
	protected global::System.Web.UI.WebControls.Label lblEnterpriseLegal;
	protected global::System.Web.UI.WebControls.Label lblEnterpriseAddress;
	protected global::System.Web.UI.WebControls.Label lblEnterprisePhone;
	protected global::System.Web.UI.WebControls.Label lblDateTimeCreated;
	protected global::System.Web.UI.WebControls.Label lblUserCreator;
	protected global::System.Web.UI.WebControls.Label lblDateTimeModified;
	protected global::System.Web.UI.WebControls.Label lblUserModified;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblOrgId;


       
    }
}
