//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Inv_Rcv_Bill_Hd {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtId;
		protected global::System.Web.UI.WebControls.TextBox txtRcvType;
		protected global::System.Web.UI.WebControls.TextBox txtRcvUserId;
		protected global::System.Web.UI.WebControls.TextBox txtRcvUserName;
		protected global::System.Web.UI.WebControls.TextBox txtRcvPhone;
		protected global::System.Web.UI.WebControls.TextBox txtRcvDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtRcvReason;
		protected global::System.Web.UI.WebControls.TextBox txtRcvAddress;
		protected global::System.Web.UI.WebControls.TextBox txtRentSubject;
		protected global::System.Web.UI.WebControls.TextBox txtRentUserId;
		protected global::System.Web.UI.WebControls.TextBox txtRentUserName;
		protected global::System.Web.UI.WebControls.TextBox txtRentPhone;
		protected global::System.Web.UI.WebControls.TextBox txtRrcBillId;
		protected global::System.Web.UI.WebControls.TextBox txtPlanRtnDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtActualRtnDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtBillStatus;
		protected global::System.Web.UI.WebControls.TextBox txtDateTimeCreated;
		protected global::System.Web.UI.WebControls.TextBox txtUserCreator;
		protected global::System.Web.UI.WebControls.TextBox txtDateTimeModified;
		protected global::System.Web.UI.WebControls.TextBox txtUserModified;
		protected global::System.Web.UI.WebControls.CheckBox chkState;
		protected global::System.Web.UI.WebControls.TextBox txtOrgId;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
