//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Inv_Rcv_Bill_Hd {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblRcvType;
	protected global::System.Web.UI.WebControls.Label lblRcvUserId;
	protected global::System.Web.UI.WebControls.Label lblRcvUserName;
	protected global::System.Web.UI.WebControls.Label lblRcvPhone;
	protected global::System.Web.UI.WebControls.Label lblRcvDateTime;
	protected global::System.Web.UI.WebControls.Label lblRcvReason;
	protected global::System.Web.UI.WebControls.Label lblRcvAddress;
	protected global::System.Web.UI.WebControls.Label lblRentSubject;
	protected global::System.Web.UI.WebControls.Label lblRentUserId;
	protected global::System.Web.UI.WebControls.Label lblRentUserName;
	protected global::System.Web.UI.WebControls.Label lblRentPhone;
	protected global::System.Web.UI.WebControls.Label lblRrcBillId;
	protected global::System.Web.UI.WebControls.Label lblPlanRtnDateTime;
	protected global::System.Web.UI.WebControls.Label lblActualRtnDateTime;
	protected global::System.Web.UI.WebControls.Label lblBillStatus;
	protected global::System.Web.UI.WebControls.Label lblDateTimeCreated;
	protected global::System.Web.UI.WebControls.Label lblUserCreator;
	protected global::System.Web.UI.WebControls.Label lblDateTimeModified;
	protected global::System.Web.UI.WebControls.Label lblUserModified;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblOrgId;


       
    }
}
