//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Topic {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txttLogo;
		protected global::System.Web.UI.WebControls.TextBox txttName;
		protected global::System.Web.UI.WebControls.TextBox txttDetail;
		protected global::System.Web.UI.WebControls.TextBox txttAuthor;
		protected global::System.Web.UI.WebControls.TextBox txttSectendDetail;
		protected global::System.Web.UI.WebControls.CheckBox chktIsDelete;
		protected global::System.Web.UI.WebControls.TextBox txttRead;
		protected global::System.Web.UI.WebControls.TextBox txttCommend;
		protected global::System.Web.UI.WebControls.TextBox txttGood;
		protected global::System.Web.UI.WebControls.TextBox txttCreatetime;
		protected global::System.Web.UI.WebControls.TextBox txttUpdatetime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
