//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Topic {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lbltLogo;
	protected global::System.Web.UI.WebControls.Label lbltName;
	protected global::System.Web.UI.WebControls.Label lbltDetail;
	protected global::System.Web.UI.WebControls.Label lbltAuthor;
	protected global::System.Web.UI.WebControls.Label lbltSectendDetail;
	protected global::System.Web.UI.WebControls.Label lbltIsDelete;
	protected global::System.Web.UI.WebControls.Label lbltRead;
	protected global::System.Web.UI.WebControls.Label lbltCommend;
	protected global::System.Web.UI.WebControls.Label lbltGood;
	protected global::System.Web.UI.WebControls.Label lbltCreatetime;
	protected global::System.Web.UI.WebControls.Label lbltUpdatetime;


       
    }
}
