//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.BlogArticle {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtbsubmitter;
		protected global::System.Web.UI.WebControls.TextBox txtbtitle;
		protected global::System.Web.UI.WebControls.TextBox txtbcategory;
		protected global::System.Web.UI.WebControls.TextBox txtbcontent;
		protected global::System.Web.UI.WebControls.TextBox txtbtraffic;
		protected global::System.Web.UI.WebControls.TextBox txtbcommentNum;
		protected global::System.Web.UI.WebControls.TextBox txtbUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtbCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtbRemark;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDeleted;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
