//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.BlogArticle {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblbID;
	protected global::System.Web.UI.WebControls.Label lblbsubmitter;
	protected global::System.Web.UI.WebControls.Label lblbtitle;
	protected global::System.Web.UI.WebControls.Label lblbcategory;
	protected global::System.Web.UI.WebControls.Label lblbcontent;
	protected global::System.Web.UI.WebControls.Label lblbtraffic;
	protected global::System.Web.UI.WebControls.Label lblbcommentNum;
	protected global::System.Web.UI.WebControls.Label lblbUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblbCreateTime;
	protected global::System.Web.UI.WebControls.Label lblbRemark;
	protected global::System.Web.UI.WebControls.Label lblIsDeleted;


       
    }
}
