//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.UserRole {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDeleted;
		protected global::System.Web.UI.WebControls.TextBox txtUserId;
		protected global::System.Web.UI.WebControls.TextBox txtRoleId;
		protected global::System.Web.UI.WebControls.TextBox txtCreateId;
		protected global::System.Web.UI.WebControls.TextBox txtCreateBy;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtModifyId;
		protected global::System.Web.UI.WebControls.TextBox txtModifyBy;
		protected global::System.Web.UI.WebControls.TextBox txtModifyTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
