//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Guestbook {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtblogId;
		protected global::System.Web.UI.WebControls.TextBox txtcreatedate;
		protected global::System.Web.UI.WebControls.TextBox txtusername;
		protected global::System.Web.UI.WebControls.TextBox txtphone;
		protected global::System.Web.UI.WebControls.TextBox txtQQ;
		protected global::System.Web.UI.WebControls.TextBox txtbody;
		protected global::System.Web.UI.WebControls.TextBox txtip;
		protected global::System.Web.UI.WebControls.CheckBox chkisshow;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
