//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.Guestbook {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblblogId;
	protected global::System.Web.UI.WebControls.Label lblcreatedate;
	protected global::System.Web.UI.WebControls.Label lblusername;
	protected global::System.Web.UI.WebControls.Label lblphone;
	protected global::System.Web.UI.WebControls.Label lblQQ;
	protected global::System.Web.UI.WebControls.Label lblbody;
	protected global::System.Web.UI.WebControls.Label lblip;
	protected global::System.Web.UI.WebControls.Label lblisshow;


       
    }
}
