//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsam.Core.Model.Models.Web.OperateLog {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.CheckBox chkIsDeleted;
		protected global::System.Web.UI.WebControls.TextBox txtArea;
		protected global::System.Web.UI.WebControls.TextBox txtController;
		protected global::System.Web.UI.WebControls.TextBox txtAction;
		protected global::System.Web.UI.WebControls.TextBox txtIPAddress;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtLogTime;
		protected global::System.Web.UI.WebControls.TextBox txtLoginName;
		protected global::System.Web.UI.WebControls.TextBox txtUserId;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
